### ISSUE TITLE
SyntaxError in iotdb-helpers/lib/d.js line 257

### ISSUE THREAD

**Issue by sjlongland** [dpjanes/iotdb-helpers#2]
Hi,

It seems your code is a little broken, `node` throws a syntax error trying to parse it:

```
$ node …/script.js 
${PWD}/node_modules/iotdb-links/node_modules/iotdb-helpers/lib/d.js:257
const deep_compose = (...ods) => {
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
…
```
https://github.com/dpjanes/iotdb-helpers/blob/master/lib/d.js#L257 has an erroneous `...` which is causing grief.

**Comment by dpjanes** [comment]
Looks like you are running an old version of Node. Try running Node6.

**Comment by sjlongland** [comment]
On 24/10/17 19:08, David Janes wrote:
> Looks like you are running an old version of Node. Try running Node6.

Unfortunately our code base doesn't support Node6.  This would have been
good to document though as the README I saw made no mention of what
version of Node was required.
